### ISSUE TITLE
Kirby 4 compatibility

### ISSUE THREAD

**Issue by arnoson** [youngcut/kirby-map#12]
Thanks for the great plugin!

I'm trying to get it to work with Kirby 4, and it the `Structure` constructor and options have changed (see the breaking changes section [here](https://github.com/getkirby/kirby/releases/tag/4.0.0-alpha.4)).

```php
 new Structure([$field->yaml()], $field->parent())
```

should become

```php
Structure::factory([$field->yaml()], ['parent' => $field->parent()]);
```

I can create a PR if you want

**Comment by youngcut** [comment]
Hello.
Thanks for your input. This fix and other things (linke search dialog) is in version 1.1.0.
