### ISSUE TITLE
Can't figure out how to add the map block to a template

### ISSUE THREAD

**Issue by julianftw** [youngcut/kirby-map#15]
Hi,

I'd like to add the map block to one of my templates, but I'm not quite sure how to do it.

I can view and edit the map in the backend just fine by adding this to my blueprint:

`wildbieneMap:
        label: Karte
        type: blocks
        fieldsets:
          - maps`

But then in the template file, Kirby won't display the map on the frontend. I tried to insert the map block via:

`<?php  $page->wildbieneMap()  ?>`

I also tried copying the snippets from the plugin folder to "snippets/blocks", but when I add the block to my template via

`<?php snippet('blocks/maps')  ?>`

I get the error "Undefined variable $block".

I'm still a beginner with Kirby so I might not understand the workflow correctly yet. How can I insert the map block so it gets displayed on the frontend?

**Comment by youngcut** [comment]
Try `$page->wildbieneMap()->toBlocks()` as described in [kirby's manual](https://getkirby.com/docs/reference/panel/fields/blocks#blocks-in-your-templates).
