### ISSUE TITLE
t is not defined

### ISSUE THREAD

**Issue by mauricerenck** [youngcut/kirby-map#8]
When using the block of kirby-map, every action results in an error `t is not defined` in marker.js.

I was able to solve this by removing `$t("empty")` with `"empty"` in Marker.vue line 8, seems like that function is not available (anymore?). Didn't want to do this as a pull request, because you might want to have a translation there, I guess.

**Comment by youngcut** [comment]
Thx for your hint. Can you tell me your Kirby-Version?

**Comment by mauricerenck** [comment]
We're currently using 3.6.5

**Comment by youngcut** [comment]
Since i didn't heard from you for a loooooong time, i assume, your problem is fixed. (Ticket closed)
