### ISSUE TITLE
Pin IDs 

### ISSUE THREAD

**Issue by janstieler** [youngcut/kirby-map#9]
Hi,
it would be great if the pins will get an ID so that I can control them from outside of the map.

Cheers

**Comment by youngcut** [comment]
Thx for your input. it's available in version 1.0.6.

**Comment by janstieler** [comment]
Hi,
I can't see the IDs I used in the panel in the frontend.
Or where will it be outputed?

**Comment by youngcut** [comment]
It's a bug and fixed in 1.0.7
